### ISSUE TITLE
Shorten types and function names

### ISSUE THREAD

**Issue by spacekookie** [soc/directories-rs#11]
This is just a suggestion and I'm wondering what you think about it. But all of the types and function names are *very* verbose.

For example `ProjectDirectories` could also just be shortened to `AppDirs` or `Base Directories` to `BaseDirs`. Also then having to say `dirs.project_config_dir` instead of just `dirs.config` feels…redundant.

So, this is just a suggestion on my part, I'm not married to any of these names. But I think shortening some of the names could make the crate a lot nicer to use.

```
BaseDirectories => BaseDirs
ProjectDirectories => AppDirs | ProjDirs | Project

let proj = Project::from_name("my_cool_tool");
proj.config()
proj.cache()
proj. ...

let downloads = BaseDirs::downloads()
// ... etc ...
```

Generally I would suggest using the non-member `::` operator instead of normal dot-notation

**Comment by soc** [comment]
@spacekookie Thanks for the suggestions, you are raising some valid points!

I retained the names from the Java port, so I thought a bit about it in the past, but not too much. Here was my original reasoning:

- One of the motivation for the more verbose function names was to avoid having the same function names on `BaseDirectories` and `ProjectDirectories` (like `config_dir` vs. `project_config_dir`). So that people who use both of them cannot introduce bugs by confusing a value of `base_dir` with a value of `proj_dir`.
- While I believe that short method names are good, I felt in this case, where it is unlikely that any function will be called more than a few times, explicit is better.
- I avoided abbreviating `BaseDirectories` and `ProjectDirectories` because from my perspective, Rust has a completely unhealthy relationship with abbreviations.
   - Not sure if it's the C heritage, but I don't feel it's just not necessary anymore with both IDEs and large amounts of memory (e. g. rustc won't run out of memory if `PathBuf` was `PathBuffer` or `vec` was `vector`)
   - Also, the huge amount of inconsistency in the Rust ecosystem is kind of concerning. While most words have only one way of writing them, there are often multiple ways to abbreviate them, and Rust devs seem to use all of them.
- Your idea about dropping the `_dir` is also a good point. I originally decided to explicitly keep the `_dir` in function names, because I expected that there would be other libraries layered above this one which would provide additional functionality, like having a `cache` function that actually represents configuration values in a map or something. I wanted to avoid having two `cache` functions, at different levels, doing different things.

Ok, that was my original rationale for the design, please feel free to point out any flaws you may find, so we can look into things more thoroughly as necessary.

The shortening of the factory functions (like `from_name`) is interesting, because I expect that I will have to redo some parts of it anyway, due to #10. I would be very happy to hear your advice on that!

The only thing I care in this regard is that the raw `from_unprocessed_string` (I know terrible name, some people have suggested something with "verbatim" instead) is kept more scary-/inconveniently-looking than the more refined functions people should be using instead.

> Generally I would suggest using the non-member :: operator instead of normal dot-notation

Thanks, I will fix that!

**Comment by spacekookie** [comment]
Well, according to the documentation the problem is that you're declaring functions in the pattern of `config_dir(&self)` which makes it a member function. Remove `&self` to make them type-functions.

Also, regarding the naming schemes it's very obviously Java-like (Most of my past jobs were as a Java engineer). But it is in a way verbose that feels very un-rustic. We can discuss different naming policies but the core issue is that I don't think it's the API's job to prevent certain kind of errors. Yes, making module names clear is important but there is always a way of overdoing it.

### What I propose

First, unify function names and get rid of bloat in the names that aren't needed. Yes, looking at the function names by themselves makes it very clear what they do. But it feels very C-like. Because in the end those functions don't exist outside of a context. So the context is `My Project` or `My Operating System`. Making the function names shorter just makes it **feel** less boilerplate-y.

Rust already uses `Dir` as an abbreviation for `Directory` and `Dirs` for `Directories` (from the stdlib). I would name the project specific type `Project` and the general system-specific `BaseDirs`. That also introduces a separation of modules.

I think there are some bad examples when it comes to Rust libraries and how they abbreviate types, yes. But I think they are the minority. In most cases Rust developers manage to not create `AwsmClTypeIfCtrl` or `MyProjectDatabaseControllerFactoryController` :wink:

So what this boils down to

```rust
impl Project {

    /// My app is called `foo`
    fn from_name(name: &str) -> Project { ... }
    
    /// My app is called `de.spacekookie.foo` (Yay Java!)
    fn from_domain_name(domain: &str, name: &str) -> Project { ... }

    fn config(&self) -> Path { ... }
    fn cache(&self) -> Path { ... }
    fn data(&self) -> Path { ... }
}
```

And for the base directory types essentially the same without constructor types

```rust
struct BaseDirs;
impl BaseDirs {

    fn home() -> Path { ... }
    fn cache() -> Path { ... }
    fn config() -> Path { ... }
    fn data() -> Path { ... }
    fn data_roaming() -> Path { ... }

    // ...
}
```

This is about decreasing the amount of bloat a developer has to write before getting started and making for a more Rustic and making the on-boarding is easy as possible for someone who might also be new to Rust and is discovering this crate in the general CLI story

**Comment by soc** [comment]
> Well, according to the documentation the problem is that you're declaring functions in the pattern of config_dir(&self) which makes it a member function. Remove &self to make them type-functions.

Mh, from my understanding, they need to be member functions, because they require the actual values from the struct to operate. Is this incorrect?

> We can discuss different naming policies but the core issue is that I don't think it's the API's job to prevent certain kind of errors. 

I guess we have to disagree on that. I spent almost half a year of deprecating and removing things from Scala. My experience is that everything that doesn't actively discourage misuse will be used incorrectly, and in the end, it causes unnecessary problems which the author (me) has to deal with.

Ok, let's see what we can figure out regarding the naming:

- I guess the major question is whether I want to have the two libraries diverge.
- If that's the case, the following things come up:
  - Shortening `Directories` to `Dir` ... Rust using `Dir` is an argument for that.
  - Maybe the `_dir` postfix can be dropped, I was always a bit uneasy with the fact that it ended with `_dir`, but returned a `Path`.
  - Not sure about dropping the `_project` from `ProjectDir` ... `ProjectDir` and `BaseDir` have intentionally different APIs to make it more obvious that they have distinct use-cases.

I'm also thinking about using `UserDir` instead of `BaseDir`, but that would only make sense if I never add APIs that return system directories (e. g. `system_config` for `/etc` similarly to the existing `config` function).

Any opinions on that?

**Comment by spacekookie** [comment]
I do like the `UserDir` instead of `BaseDir` change :+1: 

> Mh, from my understanding, they need to be member functions, because they require the actual values from the struct to operate. Is this incorrect?

Please see my edit and the links I provided for that answer :wink: 

> I guess we have to disagree on that. I spent almost half a year of deprecating and removing things from Scala. My experience is that everything that doesn't actively discourage misuse will be used incorrectly

Everything can be misused and as library developers it's obviously our job to make sure that this happens as little as possible. But there is such a thing as premature optimization and over-explanation in the API design. As someone who's almost exclusively tended to legacy code bases and fixed things nobody else knew how they worked…yea, there is such a thing as an API that tries to explain itself too much.

In the end it's about reducing the length of lines of code here and making the whole process of using the library more intuitive and "fluid"

**Comment by soc** [comment]
> I spent almost half a year

... should have been ...

> I spent almost half a decade

... wishful thinking I guess. Years I'll never get back.

**Comment by spacekookie** [comment]
> What a Freudian slip. Years I'll never get back.

My condolences :sweat_smile: 

Anyways, I like the suggestions you made. I think that would be a good start. Do have a look at the thing I just threw together on my fork. But obviously that's going a bit further with the re-structuring of the crate. I think in the end it would be good for usability though.

**Comment by soc** [comment]
I'm already on it. :-) Give me a few minutes!

**Comment by soc** [comment]
@spacekookie https://github.com/soc/directories-rs/pull/13

I think the first commit is fine, but after looking at the code I really dislike dropping `_dir` in the second commit.

E. g. `download` just reads like a function that downloads something, not like a function that returns the path to the download directory. Same for many of the other folders.

Also, it would be inconsistent with things like `env::home_dir` or `env::current_dir`.

I think I'll back out of the `_dir` change and keep the rest. WDYT, @spacekookie?

**Comment by soc** [comment]
/// My app is called `de.spacekookie.foo` (Yay Java!)
    fn from_domain_name(domain: &str, name: &str) -> Project { ... }

As a clarification, this is not because of Java, but because of the operating system standards on macOS.
The core idea of the factory functions is to help a developer who is only familiar with one platform to comply to the different naming rules each platform has.

In this sense `from_unprocessed_string` should probably get some documentation with a big disclaimer of

    /// Only use this function if you know what you are doing!
    /// This function is uses the given value without any adaption
    /// to operating system standards and pretty much guaranteed
    /// that it will not comply with the standards on two of the
    /// three supported platforms.

**Comment by spacekookie** [comment]
Apologies for not replying. I've been very busy the last week.

Thinking about factory functions that give a unifying interface without being too bloated, have you considered what I wrote in this comment here? https://github.com/soc/directories-rs/pull/14#discussion_r172463716

Do you have an opinion on it?

Also, considering the `_dir` suffix, I still think it'd be a lot more elegant without it. It should be `downloads`, not `download`, that was a typo on my part. But I think anyone using the directories crate isn't gonna expect it to magically download things. API level comments *are* a  thing and you can rely on your users reading them :wink: 

Also I really don't see the big deal with inconsistencies between the `env` crate and the `directories` crate. It's kinda in the name that they're dealing with…*directories*.

**Comment by soc** [comment]
Hi @spacekookie, no worries!

> Thinking about factory functions that give a unifying interface without being too bloated, have you considered what I wrote in this comment here?

Yes, I think I'm quite happy with the thing we have now. It's a single function with three arguments – yes, more than one, but I tried exactly that in the past and it didn't work too well, because it involved a lot of guessing in the implementation and trying to figure out what the user actually wanted.

> Also, considering the _dir suffix, I still think it'd be a lot more elegant without it. It should be downloads, not download, that was a typo on my part.

I have gone with `_dir` postfix, it felt more correct that way, and with this postfix I can have the same, consistent naming of directories without it sounding weird.

(I should have probably closed this bug after the recent commits, but I forgot.)

**Comment by spacekookie** [comment]
Alright, thanks for the comments. I guess this issue is done then :wink:

**Comment by soc** [comment]
Thanks for your help and advice! I think the design vastly improved with your input!
