### ISSUE TITLE
Do you want to take over the `dirs` name?

### ISSUE THREAD

**Issue by tbu-** [soc/directories-rs#21]
https://crates.io/crates/dirs

**Comment by soc** [comment]
Hey @tbu-!

First of all, thanks for creating your crate, I learned a lot from reading it, and it had a lot of impact on the design I picked in the end.

Yes, if you don't mind, I'd take over the dirs name! I'm not immediately sure whether I should move directories to dirs (because I want to keep the naming consistent between the Java and the Rust version), or whether there is some redirect etc. that crates.io supports to make dirs and directories return the same artifacts.

Nevertheless I think it would be beneficial, even if it would just enable the opportunity to reduce the set of libraries people have to consider when searching for this functionality.

Thanks,

Simon

**Comment by tbu-** [comment]
I sent you an invite on crates.io. I'm glad that the library was useful for something, it was barely used before.

>Yes, if you don't mind, I'd take over the dirs name! I'm not immediately sure whether I should move directories to dirs (because I want to keep the naming consistent between the Java and the Rust version), or whether there is some redirect etc. that crates.io supports to make dirs and directories return the same artifacts.

No problem. If you release a new version for this crate, please make sure to not break existing users; i.e. release a new 0.4 or 1.0 release, but not 0.3.*.

The only redirect that I know of would be re-exporting everything from the `directories` crate.

**Comment by soc** [comment]
Ok, thanks for the advice!

I'd probably keep everything as-is for now and spend the time until 1.0 thinking about the best way forward, and then do any change that would impact `dirs` with 1.0 at the earliest.

**Comment by soc** [comment]
@tbu- What about making `dirs` a crate that provides access to the individual directories directly (i. e. not through `BaseDirs::get`, `UserDirs::get`, ...) and making `directories` depend on it, as described in https://github.com/soc/directories-rs/issues/19?

Then people would have the choice between picking a higher-level crate (`directories`) and a slightly lower-level crate (`dirs`), with the guarantee that those crates are always in sync with each other.

**Comment by soc** [comment]
@tbu- https://github.com/soc/dirs-rs – what do you think?

**Comment by tbu-** [comment]
Sounds good. :)

**Comment by soc** [comment]
@tbu- Is there a way to print a warning message during compilation that informs people that dirs 0.3.1 and dirs 1 are different?

**Comment by soc** [comment]
@tbu- Thanks for your help and the offer of the dirs crate! I just released dirs 1!
