### ISSUE TITLE
BSD Support

### ISSUE THREAD

**Issue by wezm** [soc/directories-rs#30]
BSD systems (FreeBSD, NetBSD, OpenBSD, etc.) all follow the freedesktop specifications too so should be handled in the same way the crate currently supports Linux.

Since there are many OSes that follow this spec (Linux, BSD, Redox, Solaris, Illumos, etc) it might make sense to have the crate default to the "lin" module and only white list exceptions like Windows and macOS. That way the crate won't need to be updated each time someone uses it on a new target.

**Comment by soc** [comment]
Hi @wezm! I believe that defaulting to the lin module is what happens since https://github.com/soc/directories-rs/commit/70055e4eaccb7712db1d1e2b1561961fdfc7d30f already, but I could have missed or misunderstood something. Are there any additional changes that need to be made (either in the code or in the documentation)?
Thanks!

**Comment by wezm** [comment]
Neat! I'm glad it works as I was expecting :+1: Sorry for the noise.

I think what led me astray was the following in the README (no mention of other OSes being supported):

>     on Linux, Windows (≥ Vista) and macOS.
> 
> The library provides the location of these directories by leveraging the mechanisms defined by
> 
>     the XDG base directory and the XDG user directory specifications on Linux
>     the Known Folder API on Windows
>     the Standard Directories guidelines on macOS

and the module being called `lin`.
