### ISSUE TITLE
Make `ProjectDirs` return temporary directories for testing

### ISSUE THREAD

**Issue by kraai** [soc/directories-rs#42]
I'm creating a command-line application that stores its data in the locations returned by `ProjectDirs`.  In order to test the application without affecting the user's data, I'd like to be able to make `ProjectDirs` return temporary directories when the application is run during testing.  I think that setting the `XDG_...` environment variables would work on Linux and setting the `HOME` environment variable would work on macOS, but I don't see a way to do this on Windows.  Would adding a standard way to do this to `directories-rs` be welcome?  Do you have any suggestions for how to do so?

**Comment by soc** [comment]
@kraai Hi Matt, thanks for the suggestion! It might be possible to do with some compile-time if-def, but what do you think about also reading the `%USERPROFILE%` on Windows?

The only reason directories is not using it is because I lack the operating system and the knowledge of how the variable is used in general on Windows. That could close the gap regarding the configurability on Windows and allow easily overriding the folders on all operating systems.

What do you think?

**Comment by kraai** [comment]
I'll look into `USERPROFILE` on Windows.

It worries me a little for my test suite to have to know how to override how `directories` works on each platform.  I'm afraid that if `directories` were to change how it works or if the test suite were to be run on a new platform, the test suite could fail to override `directories` correctly and wipe out the user's data.

How about including an API which would allow the caller to specify a temporary directory and which would set or unset whatever environment variables are required to make `directories` use that temporary directory?

**Comment by soc** [comment]
> I'm afraid that if directories were to change how it works or if the test suite were to be run on a new platform, the test suite could fail to override directories correctly and wipe out the user's data.

How could this happen? This library neither creates nor deletes any directories. It doesn't write to the file system at all!

> How about including an API which would allow the caller to specify a temporary directory and which would set or unset whatever environment variables are required to make directories use that temporary directory?

The problem is that you can't really specify a temporary directory in a way that works across all platforms, so you are at the same position as overriding the individual envs in the first place, I fear ...

Maybe it would be possible to add some if-def for the debug build and consider some additional "consistent" env var in debug builds? (With the caveats mentioned above...)

**Comment by HeroicKatora** [comment]
@kraai A previous software project was in a similar position but with another library. In the end, we realized that if the tests should simulate *user* experience that logic should not have an extra code path for a particular test case. As such I suggest the following, library independent alternatives:

* Use another user account for testing
* Test in a container or simulated environment (e.g. docker, lxc, qemu)
* Integrate the above into continuous integration (CI)

This has advantages even beyond not overwriting your own user files by accident:

1. The environment (and thus the tests) can be put into a clean state, avoiding accidental depdendency on previous test runs such as requiring existing files in some cases where a create flag was not set for an `open` call.
2. Your integration tests do not have to be changed, or changed much less, if your integration environment changes. This should make it possible to more quickly test a bigger range of deployment environments.
