### ISSUE TITLE
Support for using ~/.config on Mac for command line apps

### ISSUE THREAD

**Issue by lavifb** [soc/directories-rs#47]
While not the official Apple sanctioned place for config files, the standard on the command line for MacOS tends to be using the Linux style `~/.config` for config files. Can we add support for using `~/.config` on Mac?

There is more discussion here:
https://github.com/rust-lang-nursery/cli-wg/issues/7#issuecomment-439223000

**Comment by cjbassi** [comment]
Do cli apps on Mac also use the XDG data folder (`~/.local/share/`) and cache folder (`~/.cache/`)? If so, I'm wondering if the better method would be to instead use https://github.com/whitequark/rust-xdg for command line applications, and use directories-rs for gui applications, assuming cli apps on windows use xdg too.

**Comment by lavifb** [comment]
Yeah that definitely works for Mac but then it doesn’t for Windows. (I don’t have a windows machine but as far as I can tell XDG is not the standard there)

**Comment by lavifb** [comment]
For instance, Neovim does not use XDG on windows 
https://neovim.io/doc/user/starting.html#vimrc

**Comment by FranklinYu** [comment]
I want to add [my answer on Stack Overflow](https://stackoverflow.com/questions/3373948/equivalents-of-xdg-config-home-and-xdg-data-home-on-mac-os-x/52749090#52749090) to the reasons of using `~/.config` for CLI.

**Comment by retep998** [comment]
>assuming cli apps on Windows use xdg too

Nothing on Windows uses XDG.

**Comment by soc** [comment]
I will not support this:

Either we also change cache folders and therefore force everyone to add exclusions to macOS' backup software (`Library/Caches` is excluded, `.cache` isn't) or spread the folders into completely different places in the filesystem.

As a general advice for macOS devs: If you are developing on their platform, do what the platform owners tell you. They are the lords, you are the share-croppers.

**Comment by soc** [comment]
I closed this, but anyone should feel free to reopen if that person has new information.

**Comment by FranklinYu** [comment]
If I manually set the environment variable `$XDG_CONFIG_HOME` would it be respected on macOS?

**Comment by lilyball** [comment]
Cross-platform CLI apps that write to ~/Library on macOS feel wrong to me. I would really like my CLI apps to use `~/.config` even on macOS. Using ~/Library/Caches is much more reasonable since, as a user, I don't have to care about that, and it won't get backed up by Time Machine. But configuration and user data should go into the appropriate CLI location.

**Comment by DanCardin** [comment]
It feels like respecting a set value for `XDG_*_HOME` in all cases would be ideal, and then falling back to the existing directories when unset.

While I would probably opt to not set `XDG_CACHE_HOME` because i don't care and thus get the existing behavior (but if someone wants to opt into a specific spot, go for it), I very much **do** want to set `XDG_CONFIG_HOME` (as much of the point of a standard location like is so that I can port my config folder to some other machine)

**Comment by FranklinYu** [comment]
> It feels like respecting a set value for `XDG_*_HOME` in all cases would be ideal, and then falling back to the existing directories when unset.

Agree. When users set `XDG_CONFIG_HOME` themselves, it’s a clear indicator that this user wants configuration to be placed there. We should assume that user knows what he is doing, instead of making the decision for them.

**Comment by lilyball** [comment]
I would be very surprised if a program behaved differently with `XDG_CONFIG_HOME=$HOME/.config` versus `XDG_CONFIG_HOME` being unset.

**Comment by soc** [comment]
> If I manually set the environment variable `$XDG_CONFIG_HOME` would it be respected on macOS?

No, it won't.

**Comment by cjbassi** [comment]
Suggestion: Add an argument to the `ProjectDirs` constructor called `use_xdg_on_macos: bool` so that users can specify if they want that feature or not. That way directories-rs can work as expected for both GUI and CLI apps since users who can specify which one they want based on the type of program they are creating.

**Comment by OJFord** [comment]
> As a general advice for macOS devs: If you are developing on their platform, do what the platform owners tell you. They are the lords, you are the share-croppers.

OK, so if they tell me that their `$XDG_CONFIG_HOME` is at `/Users/lord/.config`, I should use that. Except, with `dirs-dev`, I can't.

I am a macOS 'platform owner', as well as Linux, and my `$XDG_CONFIG_HOME = $HOME/.config` (i.e. explicitly, not the unset fallback per spec) on both.

I can.. _understand_ wanting to use Library or whatever if nothing's specified, but if `$XDG_*` are actually present in the environment, using Library is knowingly doing what the user doesn't want.

(By the way, I found [etcetera](https://docs.rs/etcetera/0.3.2/etcetera/index.html), which supports different 'strategies' for choosing base directories, such as an `Xdg` strategy, and the _default_ is what we're all after - something Windowsy on Windows, and XDG on everything else. (But even if that default changes, the `Xdg` strategy is there and could be used even on Windows if you wanted.))

**Comment by poliorcetics** [comment]
The justification for refusing this feels *very* wrong to me. Apple is not all-knowing and users that are setting `XDG_*` variables can be expected to know what they are doing and/or use CLI tools for which they want to save the configuration files to a VCS repo.

I can understand the default case not respecting `XDG_*` vars since it's not recommended behaviour but a new module `xdg` that respects it would be nice, especially for CLI apps.

**Comment by poliorcetics** [comment]
See https://github.com/dirs-dev/dirs-rs/pull/40

**Comment by OJFord** [comment]
@soc Apple does not tell you not to use environment variables to configure where data is stored on 'their' devices, that's absurd.

**Comment by soc** [comment]
@OJFord Apple defines where various kinds of data are stored. The rules do not contain an "in case you want to make up your on conventions ..." section.

**Comment by OJFord** [comment]
It defines defaults and standard practices.

Sane CLI/TUI and other programmer tools in particular respect XDG if used.

Hell, many use the $HOME or $HOME/.config without the option; respecting neither Apple nor XDG's standard.

I have absolutely no idea why you would think it makes sense togo out of your way to ignore (based on the platform) an environment variable explicitly set by the user. Is Apple paying you to uphold such ideals?

I don't currently have any macOS systems, so I don't care that much, I just think this is absurd, and I wouldn't use this crate for my own tools on that basis; not wishing it on any Mac users I may have.

**Comment by eugenesvk** [comment]
>As a general advice for macOS devs: If you are developing on their platform, do what the platform owners tell you. They are the lords, you are the share-croppers
> I closed this, but anyone should feel free to reopen if that person has new information.

Let's try to parse the words of the macOS lord (__emphasis__ mine)[src](https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html#//apple_ref/doc/uid/TP40010672-CH2-SW6), that might also be new information to some who can reopen :)
>### Where You Should Put Your App’s Files
>...
>- Put user data in Documents/. User data generally includes any files you might want to __expose__ to the user—anything you might want the __user__ to __create__, import, delete or __edit__
>- Put __app-created__ support files in the Library/Application support/ directory. In general, this directory includes files that the app uses to run but that should remain __hidden from the user__. This directory can also include data files, configuration files, templates and modified versions of resources loaded from the app bundle


So if a cli __app__ __manages__ (i.e. creates/edits/deletes them) the configs, then `Application support` is fine and in accordance with the express wishes of Apple.

However, if it's the common case for cli tools where __the user__ is actually __managing__ the files, then you're breaking your maxim by disrecpecting the wishes of the platform owners and using the wrong folder!

Of course, strictly following the rules won't get you to the option of listening to the users and respect their `$XDG_CONFIG_HOME` wishes, but that's still not as bad as explicitly breaking the them! :)

**Comment by utkarshgupta137** [comment]
I think the issue boils down to app-managed vs user-managed files:
- As mentioned by @eugenesvk above, according to the Apple guidelines, `~/Library/Application Support` is the wrong location for files the user is meant to access/edit. It is specifically for app-managed files. So if we want to follow their guidelines, this crate should make a distinction between config files that the app manages & config files that the user manages & not use `~/Library` for the latter.
- Setting aside Apple guidelines, one would expect that CLIs written using Rust will follow the same conventions rust does. rustup & cargo **by default** use `~/.rustup` & `~/.cargo` for their files. So by choosing to not even **allow** the developers or the users to make this choice, this crate goes against rust "conventions" as well.
- Setting aside Rust conventions too, I've honestly never used any CLI which expects me to edit files inside the `~/Library` folder. Most tools use `~/Library/Application Support` for app-managed files, but all of them store user-editable files in $HOME or $XDG_* locations. Examples: bash/zsh/fish, ssh, git, gnupg, rustup/cargo, npm/pnpm/yarn, docker, gocli, conda, vim/neovim, awscli, azurecli - just to name the ones I've installed on my system.

Given the above, the crate right now is only useful if one doesn't want to expose any config files to the user i.e. mostly GUI applications. But this crate is also being used in a lot of CLI tools written in Rust & most of them have open issues or workarounds related to this crate. Eg: https://github.com/sharkdp/fd/pull/575, https://github.com/sharkdp/bat/pull/491, https://github.com/Schniz/fnm/issues/622, https://github.com/ClementTsang/bottom/pull/182, https://github.com/Canop/broot/issues/103, https://github.com/helix-editor/helix/pull/2135, https://github.com/Canop/bacon/issues/76. These are only a few examples, I stopped searching after "h".
I understand that this crate wants to do "the right thing" by trying to follow OS guidelines, but the end result is that many rust CLI tools behave very differently to almost all other CLI tools & on top of that each CLI dev has to create (& maintain) their own workaround for this issue or leave their users unsatisfied.

What are not solutions:
- Users should just deal with it: Having a special location just for rust tools makes it difficult to manage/backup/sync config files for the users. Having all configs in `~/.config` makes it as easy as syncing a single folder. It is not possible to sync `~/Library/Application Support` since it contains a lot of large files from mostly GUI applications & the same location is used for both "data" & "config". It also makes it difficult to have common dotfiles across linux & mac. The space in the name is also annoying & some tools may even break due to it.
- Users should not use macOS: Many devs don't have a say in the matter. Most of us are installing these tools on work laptops & don't have a say in the OS/ecosystem. And if this is the only solution offered by this crate - then it shouldn't claim to support macOS or only claim partial support.
- Devs should use another crate: This crate has been thoroughly tested & maintained by the community. There are no crates that come even close in terms of the number of downloads. Migrating from this crate to another is not only a chore for the devs but also a risk since there have already been multiple forks of this crate that have later been abandoned. Since most tools have a strict breaking changes policy, any other crate will have to at least have all the functionality of this crate - so basically a fork.

#

I think these are strong arguments for why Devs & Users would want to use XDG paths on macOS for CLI tools. For most users, it is not a question of what they prefer or personal taste - but of convenience & functionality.
Considering the number of crates in the ecosystem which depend on this crate & the number of users who've run into this issue - I think it is just wrong to simply dismiss the Why & not even consider the How.

If the position of the maintainers is still that they don't want to support this use case, then at the very least they should make it clear in the readme that this crate is not recommended for user-managed config locations & perhaps link to this issue so that new tool devs can make an informed decision - at least until there is an alternative crate (in the comparison section) or new maintainers.

P.S. I've not included any possible solutions to the problem since it seems like no solutions were ever considered before closing the issue. There are many possible solutions that won't require a breaking change from this crate or even the CLI tools.

**Comment by OJFord** [comment]
Excellent description @utkarshgupta137 👍🏻.

I only wanted to add that it just occurred to me with your CLI vs GUI description, I think when @soc writes things like:
> As a general advice for macOS devs: If you are developing on their platform, do what the platform owners tell you. They are the lords, you are the share-croppers.

this is coming from the perspective that 'macOS devs' are creating apps for macOS to be used by (largely) non-developer users.

Whereas I assume anybody complaining that XDG isn't being respected is themself a developer _using_ macOS; either writing their own tool, or a developer tool that another 'macOS dev' created.

With that in mind, I understand the perspective a bit more - before I thought it was saying 'you are a mere user of macOS, you don't own your hardware, Apple does, do what the company says'. That said, a lot of developers use macOS, a lot of developer tools support macOS, and most developer tools respect (or almost respect, or dump in `$HOME` but certainly not `Library/Application Support`) the XDG desktop dirs spec.

I'd refine/clarify my:
> I wouldn't use this crate for my own tools on that basis; not wishing it on any Mac users I may have.

that I wouldn't use it for _developer tools_. If I was writing a calendar app or menu bar widget or whatever, yes absolutely, Application Support does make sense, I'd have no problem using `directories-rs` for that sort of application.

**Comment by utkarshgupta137** [comment]
@OJFord agreed, but with a minor caveat: GUI vs TUI/CLI is not the same as app-managed vs user-managed. Almost all GUI apps have app-managed configs & almost all CLI tools have user-managed configs.
- `~/Library/Application Support` is absolutely the correct place for GUI apps with GUI settings. I believe these are the apps targeted by the Apple documentation.
- IMO, CLI tools with user-managed configs should always fallback to `~/.config`, if not use that by default.
- There are some GUI apps with user-managed configs: Many terminal emulators & some code editors (like neovim clients) don't have a settings GUI & instead rely on users to manage conf files. Alacritty, Wezterm, Neovide are the ones I'm aware of & all of them use either $HOME or $XDG by default. Also, it is common to manually edit conf files in some apps like VSCode.
- There are also some CLI tools with app-managed configs: GnuPG & awscli are great examples. Both of them require initial setup & users are encouraged to use the CLI itself for managing the configuration rather than editing them manually. git/rustup/conda are a few examples that include interfaces for changing settings, but it is not uncommon to edit the conf files directly. All of these also use $HOME or $XDG by default.

I think it is clear that most apps/tools which expect the users to manually edit the files sooner or later default to using $HOME or $XDG.
Again, I think the app-managed config vs user-managed config should definitely be part of the README. Most devs who are accustomed to Windows/Linux may not realize this distinction & assume that they can use this crate for user-managed configs since this distinction isn't really applicable to Windows/Linux.

**Comment by poliorcetics** [comment]
Even app-managed config can have a place in `~/.config`, though it's true it's much rarer. `git` is an example where it's possible to do (almost ?) everything through the CLI but I wouldn't want it's config in `~/Library/Application Support`

**Comment by utkarshgupta137** [comment]
I'm not hopeful that @soc or any other maintainers are going to respond, so I'm trying to revive the *-next forks. I've had a brief conversation with @Dylan-DPC, who is one of the owners of *-next crates and is also a Rust Team Member & I think he is on board with accepting ***some*** change into those crates.
I've created 3 PRs to re-sync the forks with these crates: https://github.com/xdg-rs/dirs/pull/64, https://github.com/xdg-rs/dirs/pull/65, https://github.com/xdg-rs/dirs/pull/66. I think once those are merged, we can have a release so that the remaining users of these crates can migrate to the forks without any breakage concerns. Meanwhile, we can discuss the new API so that it is easy for both devs & users to make the changes for macOS over at https://github.com/xdg-rs/dirs/issues/45.

**Comment by sdavids** [comment]
> Either we also change cache folders and therefore force everyone to add exclusions to macOS' backup software (`Library/Caches` is excluded, `.cache` isn't) or spread the folders into completely different places in the filesystem.

You can address that issue by setting an extended attribute after you create the directory:

```shell
xattr -w com.apple.metadata:com_apple_backup_excludeItem \
  com.apple.backupd "${XDG_CACHE_HOME}"

xattr -w com.apple.metadata:com_apple_backup_excludeItem \
  com.apple.backupd "${XDG_RUNTIME_DIR}"
```

**Comment by soc** [comment]
@sdavids This library does – by design – neither create directories nor check whether they exist. Mutating extended attributes is not going to happen.

**Comment by adriangalilea** [comment]
I do understand the rationale of @soc as much as I hate the outcome.

Every time I see `~/Library/Application Support` I get triggered: absurdly long names, uppercase, spaces in between that cause all sort of annoying scaping headaches...

I legit don't care if my computer crashes and burns and/or all my life's work's get's deleted as long as I can avoid using MacOS designated default dirs, I would take all the blame that came with it, but of course doing it as a Library that aims to do one thing would mean having to deal with all those user errors constantly, so I can't blame @soc for not wanting to cross that path, after all, is a MacOS flaw, and we should point our forks towards that porch. But of course nothing would change, just like it still has the worst Window Management on all the OS's available.

But while I respect the decision, and judging by the amount of petitions, why not allow for an env var that bypassed the OS detection? Wouldn't it be good for debugging too?

The only alternative would be switching to [etcetera](https://docs.rs/etcetera/0.3.2/etcetera/index.html), right?

**Comment by DanCardin** [comment]
I have personally switched to etcetera over this, and i think it works perfectly well, with a nice API.

The main "problem" is, for whatever reason, new tools seem to tend to choose this lib by default, not realizing the side effect; then receive bug reports about the macos behavior afterward (like nushell). And then either manually work around it, like i've seen a few tools do, or else feel stuck because it would result in wide ranging breaking changes to switch (like nushell, who's issue has been open for 5 years).

At the same time, this library is **farly** clear in the readme about what it provides, and it's not in its own best interests to specifically call out this behavior any more clearly...

**Comment by soc** [comment]
> Every time I see ~/Library/Application Support I get triggered: absurdly long names, uppercase, spaces in between that cause all sort of annoying scaping headaches...

Can't you create a symlink if that's your issue?

**Comment by adriangalilea** [comment]
> Can't you create a symlink if that's your issue?

Nope, I share my dotfiles on mac and linux, in fact my ~ is a git repo. So no, I use XDG paths for everything I use and favor software that honors XDG envs even on mac. Went as far as to [create a golang app just for being able to set XDG dirs on linux and mac](https://github.com/adriangalilea/xdg-dirs) and [my dotfiles are also public](https://github.com/adriangalilea/dotfiles-rpi) which I use in both systems atm, and I'm so happy about that workflow.

**Comment by soc** [comment]
Not sure I get that – if you symlink `~./config` to `~./Library/Application Support` your tool wouldn't even have to care about macOS having different rules, would it?

I'd imagine the bigger issue you have is that the application naming rules are different between Linux and macOS, i. e. your application `FooBar` uses a `foobar` directory on Linux, but `com.something.FooBar` on macOS.

Do your tool use some kind of mapping file that translates between naming on Linux and naming on macOS?

**Comment by ssokolow** [comment]
I think the "in fact my `~` is a git repo." part is the key detail.

It sounds like they don't go with my "`~/.profile_repo` is a git repo and `~/.profile_repo/install.py` sets up/updates symlinks" approach.

**Comment by adriangalilea** [comment]
> I think the "in fact my `~` is a git repo." part is the key detail.

Yup

> It sounds like they don't go with my "`~/.profile_repo` is a git repo and `~/.profile_repo/install.py` sets up/updates symlinks" approach.

Not sure I got that part

> (An approach I take because it keeps `git diff` or `git gui` limited to only the files I've chosen to version without needing to use `.gitignore` to blacklist every single directory/file that I *don't* want to show up.)

You should look into stow then. I essentially .gitignore `*`and then whitelist things with `!foo`

I don't do any mapping, just all my stuff uses XDG dire. And `~` is literally a repo which I just use like you would any other repo so my config is versioned, backed up, with 0 dependenciescies, across all my unix systems. The only thing is that I need to install the software differently but I'm also automating that up. i just run 2 commands and my system is ready to go weather it be a rpi, vps, or fresh mac install. Then I git pull at the start of my .zshrc so everything is always up to date when I login to the system.

**Comment by soc** [comment]
> I don't do any mapping, just all my stuff uses XDG dire. And ~ is literally a repo which I just use like you would any other repo so my config is versioned, backed up, with 0 dependenciescies, across all my unix systems.

So your whole scheme not only requires that the applications you use are poorly ported to macOS, but also that the application authors never improve on that? 😦

**Comment by DanCardin** [comment]
> So your whole scheme not only requires that the applications you use are poorly ported to macOS, but also that the application authors never improve on that? 😦

you're putting a lot of assumption and assertion about how macos **CLI** applications should and should not act, with (imo) very little evidence to support that things **should** act that way, and no other way.

Swiftlang's 1st party package manager supports XDG on macos. Also homebrew does, as an example of a piece of CLI software (originally) explicitly designed for macos. As do numerous other apps, both CLI and otherwise that have gotten feedback from enough people to decide to support it.

also https://github.com/nushell/nushell/issues/893#issuecomment-2125954485

> That said, I'm pretty surprised to see this has remained open for 5 years when the solution is so simple, especially considering the resistance to changing it seems to be on ideological grounds rather than practical ones.
> 
> I'm also puzzled by those quoting the [macOS Library Directory Details](https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/MacOSXDirectories/MacOSXDirectories.html#//apple_ref/doc/uid/TP40010672-CH10-SW1), which say this about Application Support:
> 
>     Contains all app-specific data and support files. These are the files that your app creates and manages on behalf of the user and can include files that contain user data.
> 
> It may be a little bit subtle to those unfamiliar with macOS development, but the use of "app" is very specific here, and nushell is not an app. (If it was, it would have a bundle ID, it would be installed in /Applications, etc.)
> 
> The [File System Basics](https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html#//apple_ref/doc/uid/TP40010672-CH2-SW1) document that has also been referenced says the same thing:
> 
>     An app might use this directory to store a modifiable copy of resources contained initially in the app’s bundle. A game might use this directory to store new levels purchased by the user and downloaded from a server.
> 
>     All content in this directory should be placed in a custom subdirectory whose name is that of your app’s bundle identifier or your company.
> 
> Again, note the references to a bundle and a bundle identifier — these are things that nushell does not have because nushell isn't an app!

and

> "These are the files that your app creates and manages on behalf of the user" seems more important to me than bundle id, config files are managed directly by the user and not "on behalf of the user" ?

**Comment by soc** [comment]
Ok, that argument.

**Comment by ssokolow** [comment]
Yeah. By that reasoning, it sounds like `~./Library/Application Support/<Bundle ID>` is the counterpart to Flatpak's `~/.var/app/<App ID>` and nobody argues that non-Flatpak applications should put their data under `~/.var/app/`.

**Comment by ssokolow** [comment]
> You should look into stow then. I essentially .gitignore `*`and then whitelist things with `!foo`

Perhaps, but I generally prefer not to add new dependencies when I'm doing OK with what I have.

> I don't do any mapping, just all my stuff uses XDG dire. And `~` is literally a repo which I just use like you would any other repo so my config is versioned, backed up, with 0 dependenciescies, across all my unix systems. The only thing is that I need to install the software differently but I'm also automating that up. i just run 2 commands and my system is ready to go weather it be a rpi, vps, or fresh mac install. Then I git pull at the start of my .zshrc so everything is always up to date when I login to the system. Without any extra steps. And all my aliases, functions and cli tools are there.

I use Ansible playbooks inside my repo for that. Bear in mind that my repo isn't really something I use as a roaming profile... more a template for bringing up user profiles on new machines, plus some Ansible playbooks for installing the system images, that gets overlaid locally with the machine-specific or sensitive bits and then persisted via backups.

(Heck, I had to restore from my playbook and a whole-`$HOME` nightly `rsync` backup a few months ago. I found it so irritating that I now boot via ZFSBootMenu, have one of my tiers of backup being an hourly ZFS snapshot sync to a ZRAID mirrored pair, and am preparing to install the RMA'd NVMe drive as a ZRAID mirror for the replacement NVMe drive that I rush-ordered so I'd only have to live off my laptop for two days.)

**Comment by soc** [comment]
> Yeah.

It's just that I heard variations of "here is my very specific reading of rules such that *mysteriously* the subset of applications *I care about* is exempt" ... for more than 10 years.

This is the library for the 99.8% of people who either want things to work consistently or do not want to care because all things work consistently.

It's not the library for the 0.2% of people that have to have their own special carve-out from the standard approach and subsequently ruin things for everyone else.

**Comment by lu-zero** [comment]
Being somebody that uses both linux and macos, I do find way more consistent if I can keep it in sync w/out having to deal with trying to move the configurations in another place just because of "the rules" that apparently even an Apple product like Swift do not interpret that way...
